[package]
name = "rpack"
version = "0.1.0"
edition = "2021"
authors = ["Julian Aßmann <kontakt@julianassmann.de>"]
description = "A simple rectangle packer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
